export const BRANDING = {
  appDisplayName: 'Passeo',

  pdf: {
    producer: 'Passeo App',
    creator: 'Passeo App',
    footerBrandText: 'Generated by Passeo',
    watermark: {
      line1: 'Passeo',
      line2: 'FREE VERSION',
    },
  },
} as const;
