// Free Version Limits
export const FREE_MAX_PHOTOS = 20;
export const FREE_SESSION_LIMIT = 50;

// Watermark
export const WATERMARK_TEXT = 'Generated by Passeo – Free Version';

// Feature Flag Map
export const PRO_FEATURES = {
  unlimitedPhotos: true,
  removeWatermark: true,
  handwrittenSignature: true,
};

// ── Feature Gate Helpers ──────────────────────────────────────────────
// Pass isPro from useProStatus(). All gating logic lives here — do NOT
// scatter isPro checks across screens.
//
// NOTE: session report export is intentionally ALWAYS allowed (not listed).

export function canAccessFullHistory(isPro: boolean): boolean {
  return isPro;
}

export function canAccessSummaryReports(isPro: boolean): boolean {
  return isPro;
}

export function canAccessMemberHistory(isPro: boolean): boolean {
  return isPro;
}

export function canAccessAuditLogs(isPro: boolean): boolean {
  return isPro;
}
