// Free Version Limits
export const FREE_MAX_PHOTOS = 20;

// Watermark
export const WATERMARK_TEXT = 'Generated by Passeo – Free Version';

// Feature Flag Map
export const PRO_FEATURES = {
  unlimitedPhotos: true,
  removeWatermark: true,
  handwrittenSignature: true,
};
