// Free Version Limits
export const FREE_SESSION_LIMIT = 50;

// Watermark
export const WATERMARK_TEXT = 'Generated by Passeo – Free Version';

// Feature Flag Map
export const PRO_FEATURES = {
  removeWatermark: true,
  handwrittenSignature: true,
};

// ── Feature Gate Helpers ──────────────────────────────────────────────
// Pass isPro from useClubSubscription(), not useProStatus().
// The backend club subscription status is the source of truth for Pro gating.
// useProStatus() reads from a local AsyncStorage cache and must NOT be used
// to gate Pro features.
//
// Correct pattern:
//   const { status } = useClubSubscription(clubId);
//   const isPro = status?.isPro ?? false;
//
// Store purchase history is only used for purchase/restore flows.
// All gating logic lives here — do NOT scatter isPro checks across screens.

export function canAccessFullHistory(isPro: boolean): boolean {
  return isPro;
}

export function canAccessSummaryReports(isPro: boolean): boolean {
  return isPro;
}

export function canAccessMemberHistory(isPro: boolean): boolean {
  return isPro;
}

export function canAccessAuditLogs(isPro: boolean): boolean {
  return isPro;
}
